# Generated by Django 5.0.6 on 2024-06-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='prewiew',
            new_name='preview',
        ),
    ]
