# Generated by Django 5.0.6 on 2024-07-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
